INSERT INTO blog_posts (
  title,
  slug,
  excerpt,
  content,
  content_html,
  cover_image,
  category,
  tags,
  author_name,
  status,
  is_featured,
  published_at,
  reading_time,
  view_count,
  meta_title,
  meta_description,
  canonical_url,
  related_course_ids
) VALUES
  (
    'How to Learn React in 2026',
    'how-to-learn-react-2026',
    'A practical beginner roadmap for learning React, building real projects, and preparing for frontend jobs.',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Start with the fundamentals"}]},{"type":"paragraph","content":[{"type":"text","text":"React becomes easier when your JavaScript basics are strong. Focus first on components, props, state, events, arrays, objects, and asynchronous code."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Build small projects"}]},{"type":"paragraph","content":[{"type":"text","text":"After learning the basics, build a portfolio with practical interfaces: dashboards, forms, API-driven pages, and reusable UI components."}]}]}'::jsonb,
    '<h2>Start with the fundamentals</h2><p>React becomes easier when your JavaScript basics are strong. Focus first on components, props, state, events, arrays, objects, and asynchronous code.</p><h2>Build small projects</h2><p>After learning the basics, build a portfolio with practical interfaces: dashboards, forms, API-driven pages, and reusable UI components.</p><blockquote><p>The fastest way to learn React is to build, break, debug, and rebuild.</p></blockquote>',
    '',
    'Tech',
    ARRAY['react','javascript','frontend'],
    'Sir Usman Ali',
    'published',
    TRUE,
    NOW() - INTERVAL '6 days',
    3,
    1240,
    'How to Learn React in 2026 | DeepSkills Blog',
    'Learn React step by step with a practical roadmap focused on JavaScript, components, projects, and job-ready skills.',
    'https://deepskills.pk/blogs/how-to-learn-react-2026',
    ARRAY['full-stack-react']
  ),
  (
    'Top Tech Career Paths for Beginners',
    'top-tech-career-paths-for-beginners',
    'Explore beginner-friendly tech career paths, the skills they require, and how to choose the right direction.',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Choose by work style"}]},{"type":"paragraph","content":[{"type":"text","text":"Frontend development, backend development, UI/UX design, WordPress, and digital marketing all reward different strengths. Choose the path that matches how you like to think and create."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Learn with projects"}]},{"type":"paragraph","content":[{"type":"text","text":"A certificate helps, but a real portfolio proves your skill. Build projects that show practical outcomes and problem solving."}]}]}'::jsonb,
    '<h2>Choose by work style</h2><p>Frontend development, backend development, UI/UX design, WordPress, and digital marketing all reward different strengths. Choose the path that matches how you like to think and create.</p><h2>Learn with projects</h2><p>A certificate helps, but a real portfolio proves your skill. Build projects that show practical outcomes and problem solving.</p>',
    '',
    'Career',
    ARRAY['career','tech jobs','skills'],
    'DeepSkills Team',
    'published',
    FALSE,
    NOW() - INTERVAL '4 days',
    2,
    820,
    'Top Tech Career Paths for Beginners | DeepSkills',
    'Discover beginner-friendly tech career paths and the skills needed to start learning with confidence.',
    'https://deepskills.pk/blogs/top-tech-career-paths-for-beginners',
    ARRAY['full-stack-react','graphic-design','wordpress-mastery']
  ),
  (
    'Laravel Skills Every Backend Developer Should Know',
    'laravel-skills-every-backend-developer-should-know',
    'A focused guide to the Laravel concepts students should master for real-world backend development.',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Understand MVC"}]},{"type":"paragraph","content":[{"type":"text","text":"Laravel is built around clean separation of routes, controllers, models, and views. Mastering MVC helps you write maintainable applications."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Practice databases and APIs"}]},{"type":"paragraph","content":[{"type":"text","text":"Backend developers should be confident with migrations, relationships, validation, authentication, and REST API design."}]}]}'::jsonb,
    '<h2>Understand MVC</h2><p>Laravel is built around clean separation of routes, controllers, models, and views. Mastering MVC helps you write maintainable applications.</p><h2>Practice databases and APIs</h2><p>Backend developers should be confident with migrations, relationships, validation, authentication, and REST API design.</p>',
    '',
    'Tech',
    ARRAY['laravel','php','backend'],
    'DeepSkills Team',
    'published',
    FALSE,
    NOW() - INTERVAL '3 days',
    2,
    540,
    'Laravel Skills Every Backend Developer Should Know',
    'Learn the Laravel backend skills students should master, including MVC, migrations, validation, auth, and APIs.',
    'https://deepskills.pk/blogs/laravel-skills-every-backend-developer-should-know',
    ARRAY['laravel-mastery']
  ),
  (
    'UI UX Principles Developers Should Learn',
    'ui-ux-principles-developers-should-learn',
    'Good interfaces are not only beautiful. They are clear, usable, consistent, and easy to understand.',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Design for clarity"}]},{"type":"paragraph","content":[{"type":"text","text":"A clean layout helps users understand what to do next. Developers should learn spacing, alignment, hierarchy, and contrast."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Respect the user flow"}]},{"type":"paragraph","content":[{"type":"text","text":"Every screen should guide users toward a goal. Strong UI/UX thinking makes your projects feel professional."}]}]}'::jsonb,
    '<h2>Design for clarity</h2><p>A clean layout helps users understand what to do next. Developers should learn spacing, alignment, hierarchy, and contrast.</p><h2>Respect the user flow</h2><p>Every screen should guide users toward a goal. Strong UI/UX thinking makes your projects feel professional.</p>',
    '',
    'Design',
    ARRAY['ui','ux','design','figma'],
    'DeepSkills Team',
    'published',
    FALSE,
    NOW() - INTERVAL '2 days',
    2,
    390,
    'UI UX Principles Developers Should Learn | DeepSkills',
    'Learn essential UI UX principles developers can use to make projects cleaner, clearer, and more professional.',
    'https://deepskills.pk/blogs/ui-ux-principles-developers-should-learn',
    ARRAY['graphic-design']
  ),
  (
    'How to Build a Portfolio That Gets Attention',
    'how-to-build-a-portfolio-that-gets-attention',
    'A practical guide to building a student portfolio that shows skill, process, and confidence.',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Show finished work"}]},{"type":"paragraph","content":[{"type":"text","text":"Your portfolio should include complete projects, not only screenshots. Add the problem, your process, tools used, and final result."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Keep it simple"}]},{"type":"paragraph","content":[{"type":"text","text":"A strong portfolio is easy to scan. Use clear project titles, short descriptions, live links, and a simple contact path."}]}]}'::jsonb,
    '<h2>Show finished work</h2><p>Your portfolio should include complete projects, not only screenshots. Add the problem, your process, tools used, and final result.</p><h2>Keep it simple</h2><p>A strong portfolio is easy to scan. Use clear project titles, short descriptions, live links, and a simple contact path.</p>',
    '',
    'Education',
    ARRAY['portfolio','students','career'],
    'DeepSkills Team',
    'draft',
    FALSE,
    NULL,
    2,
    0,
    'How to Build a Portfolio That Gets Attention',
    'Build a student portfolio that shows practical skill, project quality, and confidence to clients or employers.',
    'https://deepskills.pk/blogs/how-to-build-a-portfolio-that-gets-attention',
    ARRAY['full-stack-react','graphic-design']
  ),
  (
    'Why Project Based Learning Works Better',
    'why-project-based-learning-works-better',
    'Project based learning helps students understand real workflows, solve practical problems, and build confidence faster.',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Learning becomes practical"}]},{"type":"paragraph","content":[{"type":"text","text":"When students build real projects, they connect concepts with decisions. They learn how layouts, data, errors, deadlines, and user needs work together."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Projects build confidence"}]},{"type":"paragraph","content":[{"type":"text","text":"A completed project gives students something they can show, explain, improve, and use in interviews or freelance conversations."}]}]}'::jsonb,
    '<h2>Learning becomes practical</h2><p>When students build real projects, they connect concepts with decisions. They learn how layouts, data, errors, deadlines, and user needs work together.</p><h2>Projects build confidence</h2><p>A completed project gives students something they can show, explain, improve, and use in interviews or freelance conversations.</p>',
    '',
    'Education',
    ARRAY['learning','projects','students'],
    'DeepSkills Team',
    'published',
    FALSE,
    NOW() - INTERVAL '1 day',
    2,
    0,
    'Why Project Based Learning Works Better | DeepSkills',
    'Learn why project based learning helps students build real skills, confidence, and stronger portfolios.',
    'https://deepskills.pk/blogs/why-project-based-learning-works-better',
    ARRAY['full-stack-react','laravel-mastery','graphic-design']
  ),
  (
    'WordPress Skills That Help Freelancers Earn',
    'wordpress-skills-that-help-freelancers-earn',
    'A beginner-friendly guide to WordPress skills that are useful for client work, small business websites, and freelancing.',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Learn client-ready basics"}]},{"type":"paragraph","content":[{"type":"text","text":"Freelancers should know hosting, domains, themes, plugins, pages, forms, backups, and basic SEO. These skills solve common client needs."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Focus on delivery"}]},{"type":"paragraph","content":[{"type":"text","text":"A professional WordPress freelancer does not only install a theme. They deliver a clean, fast, easy-to-manage website."}]}]}'::jsonb,
    '<h2>Learn client-ready basics</h2><p>Freelancers should know hosting, domains, themes, plugins, pages, forms, backups, and basic SEO. These skills solve common client needs.</p><h2>Focus on delivery</h2><p>A professional WordPress freelancer does not only install a theme. They deliver a clean, fast, easy-to-manage website.</p>',
    '',
    'Tech',
    ARRAY['wordpress','freelancing','websites'],
    'DeepSkills Team',
    'published',
    FALSE,
    NOW() - INTERVAL '8 days',
    2,
    0,
    'WordPress Skills That Help Freelancers Earn | DeepSkills',
    'Discover practical WordPress skills beginners can use to build client websites and start freelancing.',
    'https://deepskills.pk/blogs/wordpress-skills-that-help-freelancers-earn',
    ARRAY['wordpress-mastery']
  ),
  (
    'How to Choose Between React and Laravel',
    'how-to-choose-between-react-and-laravel',
    'React and Laravel solve different problems. This guide helps beginners understand which path fits their goals.',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"React is for interfaces"}]},{"type":"paragraph","content":[{"type":"text","text":"React is a strong choice if you enjoy designing user experiences, building interactive pages, and working close to the frontend."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Laravel is for backend systems"}]},{"type":"paragraph","content":[{"type":"text","text":"Laravel is a strong choice if you enjoy databases, business logic, authentication, APIs, and server-side application structure."}]}]}'::jsonb,
    '<h2>React is for interfaces</h2><p>React is a strong choice if you enjoy designing user experiences, building interactive pages, and working close to the frontend.</p><h2>Laravel is for backend systems</h2><p>Laravel is a strong choice if you enjoy databases, business logic, authentication, APIs, and server-side application structure.</p>',
    '',
    'Career',
    ARRAY['react','laravel','career'],
    'DeepSkills Team',
    'published',
    FALSE,
    NOW() - INTERVAL '10 days',
    2,
    0,
    'How to Choose Between React and Laravel | DeepSkills',
    'Understand the difference between React and Laravel so you can choose the right learning path.',
    'https://deepskills.pk/blogs/how-to-choose-between-react-and-laravel',
    ARRAY['full-stack-react','laravel-mastery']
  ),
  (
    'Design Mistakes Beginners Should Avoid',
    'design-mistakes-beginners-should-avoid',
    'Simple design mistakes can make good work feel unprofessional. Learn what to avoid when creating websites and graphics.',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Too many fonts"}]},{"type":"paragraph","content":[{"type":"text","text":"Using too many fonts creates visual noise. Beginners should choose a small type system and use hierarchy through size, weight, and spacing."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Weak spacing"}]},{"type":"paragraph","content":[{"type":"text","text":"Spacing decides how polished a design feels. Give elements enough room and keep alignment consistent across sections."}]}]}'::jsonb,
    '<h2>Too many fonts</h2><p>Using too many fonts creates visual noise. Beginners should choose a small type system and use hierarchy through size, weight, and spacing.</p><h2>Weak spacing</h2><p>Spacing decides how polished a design feels. Give elements enough room and keep alignment consistent across sections.</p>',
    '',
    'Design',
    ARRAY['design','graphics','ui'],
    'DeepSkills Team',
    'published',
    FALSE,
    NOW() - INTERVAL '12 days',
    2,
    0,
    'Design Mistakes Beginners Should Avoid | DeepSkills',
    'Avoid common beginner design mistakes in typography, spacing, alignment, and visual hierarchy.',
    'https://deepskills.pk/blogs/design-mistakes-beginners-should-avoid',
    ARRAY['graphic-design']
  ),
  (
    'What Makes a Course Job Ready',
    'what-makes-a-course-job-ready',
    'A job-ready course should teach fundamentals, practical tools, project delivery, communication, and portfolio building.',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Skills need context"}]},{"type":"paragraph","content":[{"type":"text","text":"Students need to know not only what a tool does, but when to use it, why it matters, and how it fits into a real workflow."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Outcomes matter"}]},{"type":"paragraph","content":[{"type":"text","text":"A job-ready course should end with projects, feedback, confidence, and a clear next step for employment or freelancing."}]}]}'::jsonb,
    '<h2>Skills need context</h2><p>Students need to know not only what a tool does, but when to use it, why it matters, and how it fits into a real workflow.</p><h2>Outcomes matter</h2><p>A job-ready course should end with projects, feedback, confidence, and a clear next step for employment or freelancing.</p>',
    '',
    'General',
    ARRAY['courses','job-ready','skills'],
    'DeepSkills Team',
    'published',
    FALSE,
    NOW() - INTERVAL '14 days',
    2,
    0,
    'What Makes a Course Job Ready | DeepSkills',
    'Learn what makes a course practical, job-ready, and useful for students entering tech or freelancing.',
    'https://deepskills.pk/blogs/what-makes-a-course-job-ready',
    ARRAY['full-stack-react','laravel-mastery','wordpress-mastery','graphic-design']
  ),
  (
    'How Students Can Practice Coding Every Day',
    'how-students-can-practice-coding-every-day',
    'A simple daily coding practice routine for beginners who want to improve steadily without feeling overwhelmed.',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Start small"}]},{"type":"paragraph","content":[{"type":"text","text":"Daily practice works best when it is realistic. Spend time reading code, writing small functions, fixing bugs, and improving one feature at a time."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Review your work"}]},{"type":"paragraph","content":[{"type":"text","text":"At the end of each day, note what you learned and what confused you. That reflection makes the next practice session more focused."}]}]}'::jsonb,
    '<h2>Start small</h2><p>Daily practice works best when it is realistic. Spend time reading code, writing small functions, fixing bugs, and improving one feature at a time.</p><h2>Review your work</h2><p>At the end of each day, note what you learned and what confused you. That reflection makes the next practice session more focused.</p>',
    '',
    'Education',
    ARRAY['coding','practice','students'],
    'DeepSkills Team',
    'published',
    FALSE,
    NOW() - INTERVAL '16 days',
    2,
    0,
    'How Students Can Practice Coding Every Day | DeepSkills',
    'A beginner-friendly daily coding practice routine for students learning programming and web development.',
    'https://deepskills.pk/blogs/how-students-can-practice-coding-every-day',
    ARRAY['full-stack-react','laravel-mastery']
  ),
  (
    'How to Prepare for Your First Freelance Client',
    'how-to-prepare-for-your-first-freelance-client',
    'Before taking your first client, prepare your process, communication, scope, pricing, and delivery checklist.',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Define the scope"}]},{"type":"paragraph","content":[{"type":"text","text":"A clear scope protects both you and the client. Write down what you will deliver, what is not included, and when each step will happen."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Communicate clearly"}]},{"type":"paragraph","content":[{"type":"text","text":"Good freelancing depends on trust. Share progress, ask questions early, and confirm decisions in writing."}]}]}'::jsonb,
    '<h2>Define the scope</h2><p>A clear scope protects both you and the client. Write down what you will deliver, what is not included, and when each step will happen.</p><h2>Communicate clearly</h2><p>Good freelancing depends on trust. Share progress, ask questions early, and confirm decisions in writing.</p>',
    '',
    'Career',
    ARRAY['freelancing','clients','career'],
    'DeepSkills Team',
    'draft',
    FALSE,
    NULL,
    2,
    0,
    'How to Prepare for Your First Freelance Client',
    'Prepare for your first freelance client with better scope, communication, pricing, and delivery habits.',
    'https://deepskills.pk/blogs/how-to-prepare-for-your-first-freelance-client',
    ARRAY['wordpress-mastery','graphic-design','full-stack-react']
  )
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  content_html = EXCLUDED.content_html,
  cover_image = EXCLUDED.cover_image,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  author_name = EXCLUDED.author_name,
  status = EXCLUDED.status,
  is_featured = EXCLUDED.is_featured,
  published_at = EXCLUDED.published_at,
  reading_time = EXCLUDED.reading_time,
  view_count = EXCLUDED.view_count,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  canonical_url = EXCLUDED.canonical_url,
  related_course_ids = EXCLUDED.related_course_ids,
  updated_at = NOW();
